export const COMMANDS = {
    UPDATE_SHAPES: "UPDATE_SHAPES",
    ADD_SHAPE: "ADD_SHAPE",
    ADD_SHAPES: "ADD_SHAPES",
    DELETE_SHAPES: "DELETE_SHAPES",
    UPDATE_FRAMES: "UPDATE_FRAMES",
    ADD_FRAME: "ADD_FRAME",
};
